name = "Rust"

[fs]
base = "/var/lib/docker/overlay2/pa7dzgmcx2y15pdnd2jw5e227/diff:/var/lib/docker/overlay2/8487c007c019d431ef476330a49448327630d743a74201c2adae4ce7771628e6/diff:/var/lib/docker/overlay2/c053d6e00c5a2c5fef336e4b95448df888e2ff6b9ade7400cddc19b1d5fc807c/diff:/var/lib/docker/overlay2/fdaa95e8b852bee301041bd08d16c6a09efa13b93679aff994ca9e921b9491c2/diff"
workdir = "/code"

[cmd]
compile = "/usr/local/bin/rustc -o Main Main.rs"
run  = "/code/Main"
ver = "/usr/local/bin/rustc --version"
env = ["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin"]
