name = "Perl"

[fs]
base = "/var/lib/docker/overlay2/k758oan3sdbpldhi0eit9ikpm/diff:/var/lib/docker/overlay2/7dqwpde12tbejyej5syhzz1eq/diff:/var/lib/docker/overlay2/a467928a9d31383830f4483cab85fed9b58e06799ae1d3f203b0d9af3d9baaac/diff"
workdir = "/code"

[cmd]
compile = "/usr/bin/perl -c /code/Main.pl"
run = "/usr/bin/perl /code/Main.pl"
ver = "/usr/bin/perl -v"
env = ["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","DEBIAN_FRONTEND=noninteractive"]
